version: '3'
services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your@email.test.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./.letsencrypt:/letsencrypt"
    networks:
      - web

  webserver1:
    image: jwilder/whoami
    labels:
      - "traefik.http.routers.webserver1.rule=Host(`my-webserver1.wow`)"
      - "traefik.http.routers.webserver1.entrypoints=websecure"
      - "traefik.http.routers.webserver1.tls.certresolver=myresolver"
    networks:
      - web

  webserver2:
    image: jwilder/whoami
    labels:
      - "traefik.http.routers.webserver2.rule=Host(`my-webserver2.wow`)"
      - "traefik.http.routers.webserver2.entrypoints=websecure"
      - "traefik.http.routers.webserver2.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    external: true
