#!/bin/bash

set -e

# Variables
DOCKER_COMPOSE_FILE="docker-compose.yml"
HOSTS_FILE="/etc/hosts"
START_MARKER="# Generated by project"
END_MARKER="# End of section"
PROJECT_PATH=$(pwd)

# Used to add host entries to /etc/hosts
add_host_entry() {
    local hostname=$1

    echo "127.0.0.1 $hostname" | sudo tee -a "$HOSTS_FILE" > /dev/null
}

# Analyse docker-compose.yml file and add host entries
parse_docker_compose() {
    local compose_file=$1
    local services=$(yq e '.services | keys' "$compose_file" | sed -e 's/- //g' -e 's/\[//g' -e 's/\]//g' -e 's/,//g')

    for service in $services; do
        local host=$(yq e ".services.$service.labels[0]" "$compose_file" | cut -d '`' -f 2)
        if [ -n "$host"  ] && [ $host != "null" ]; then
            add_host_entry "$host"
        fi
    done
}

# Create a Docker network if it doesn't exist
create_docker_network() {
    local network_name=$1
    if ! docker network ls | grep -q "$network_name"; then
        docker network create "$network_name"
    fi
}

# Delete previous entries from /etc/hosts if they exist
remove_previous_entries() {
    if grep -q "$START_MARKER" "$HOSTS_FILE"; then
        sudo sed -i '' -e "/$START_MARKER/,/$END_MARKER/d" "$HOSTS_FILE" >/dev/null 2>&1 || true
    fi
}

# Main function
main() {
    # Check if yq is installed
    if ! command -v yq &> /dev/null; then
        echo "yq pourrait ne pas être installé. Installation..."
        brew install yq
    fi

    # Create a "web" Docker network
    create_docker_network "web"

    # Delete previous entries from /etc/hosts (for this project)
    remove_previous_entries

    # Delete the .letsencrypt directory if it exists
    rm -rf ./.letsencrypt

    # Add host entries to /etc/hosts
    echo "$START_MARKER $PROJECT_PATH" | sudo tee -a "$HOSTS_FILE" > /dev/null
    parse_docker_compose "$DOCKER_COMPOSE_FILE"
    echo "$END_MARKER" | sudo tee -a "$HOSTS_FILE" > /dev/null

    # Start the Docker containers
    docker-compose up --build
}

main
